apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  replicas: 1
  serviceMonitorSelector:
    matchLabels:
      k8s-app: prometheus
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
