apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: socks-shop-cert
spec:
  secretName: socks-shop-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - trip-socks-shop.com
