apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
spec:
  replicas: 1
  serviceMonitorSelector:
    matchLabels:
      k8s-app: alertmanager
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
